### ISSUE TITLE
Better description

### ISSUE THREAD

**Issue by bainewedlock** [regolith-linux/regolith-linux.github.io#22]
based on https://regolith-linux.org/docs/howto/time-format/, I created ./.config/regolith/Xresources file with
`i3xrocks.date.format2: yyyy`
however, now my date just disappeared. what is the format syntax?

**Comment by kgilmer** [comment]
Thanks for the bug report.  The format syntax is just what is passed to the `date` command.  So for example:

```bash
$ date +%Y
2020
```

`i3xrocks.date.format2: + %Y`

**Comment by kgilmer** [comment]
Website edit will go out with more details on the page.

**Comment by bainewedlock** [comment]
that makes sense, thanks for the quick response!
