### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by acebone** [regolith-linux/regolith-linux.github.io#23]
https://regolith-linux.org/docs/howto/time-format/

"To do so, override the i3xrocks.date.format2 Xresource key. See Xresource overrides for details."

This is really frustrating. In one line, the secret of how to change your date-format could be explained (add this line xxx to this file yyy). Instead I'm referred to at general page on overriding settings - a page that does not help me at all.

I've tried to add 

i3xrocks.date.format2 =  %R %A %d. %B %Y

to ~/.config/regolith/i3/config - that didn't work

I've added 

i3xrocks.date.format2: %R %A %d. %B %Y

to ~/.config/regolith/Xresources

That didn't work.

It turns out that xrdb -query does NOT list i3xrocks.date.format2 as a value that can be altered

It's a simple thing: I want to change my date-format. I'm not a regolith-hacker. I think that focus should be on usability in the help-files. Will it help with the task it sets out to help with? Will the user be able to perform the action that he or she wishes to perform?

I may be slow, maybe there's something I overlooked - but help-files should not require a user to be bright, alert, observant and reflecting - they should help the user accomplish what the user wishes to accomplish.

My date-format is still fubar.
:)

P.S. Forgot to put a title on this ticket - Can't edit one in, I'm sorry.

**Comment by kgilmer** [comment]
I understand your frustration @acebone .  I'll provide a complete example in the docs.  In the mean time, I was able to use your specifcation on the command line with no problems:

```bash
$ echo "i3xrocks.date.format2: %R %A %d. %B %Y" > ~/.config/regolith/Xresources
$ regolith-look refresh
> Updating already existing 'Regolith' profile
$
```

![image](https://user-images.githubusercontent.com/49683/84520473-7cf23800-ac88-11ea-9ae1-d260237df2bb.png)

Can you try what I've got here and let me know if it's still not working?

**Comment by acebone** [comment]
Thnx for answering KGilmer

I've tried

```
$ echo "i3xrocks.date.format2: %R %A %d. %B %Y" > ~/.config/regolith/Xresources

$ cat .config/regolith/Xresources 
i3xrocks.date.format2: %R %A %d. %B %Y

$ regolith-look refresh
> Updating already existing 'Regolith' profile
[SUCCESS] Reinstalled Regolith GNOME Terminal version 0.1.0 for the 'Regolith' profile!
```

The date disappears:

![Screenshot from 2020-06-13 12-56-49](https://user-images.githubusercontent.com/152805/84566935-67a70780-ad75-11ea-9bc1-28c70bd344dc.png)

Hmmm ... and now it won't show, even if I delete the Xresources file ...

**Comment by kgilmer** [comment]
Weird.  You can run the script that generates the time directly from a terminal:
```bash
$ /usr/share/i3xrocks/time 
<span color="#E6E1CF"></span><span font_desc="JetBrains Mono Medium 13" color="#E6E1CF"> 08:02 Saturday 13. June 2020 </span>
```

And you can verify what the Xresource override is set to for the time format:
```bash
$ xrescat i3xrocks.date.format2
%R %A %d. %B %Y
```

Do you get an error when running the script directly?

**Comment by acebone** [comment]
Somehow I managed to set the value of `format2` to `'%R %A %d. %B %Y'` (single-quotes included).

That is invalid according to the time-script:
```

$ /usr/share/i3xrocks/time 
date: invalid date ‘'%R %A %d. %B %Y'’
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> </span>
```
I've made sure that the format is no longer custom-defined (no Xresource-file) - but a refresh/reload/reboot does not clear the erroneous format-value. I'm pretty sure I haven't edited the global config files.

**Comment by kgilmer** [comment]
Hmmm, well this page describes which files are loaded by Regolith for Xresource values: https://regolith-linux.org/docs/reference/configurations/

Check the row `Xresources`.  One of those files has the setting.  I think you just need to remove the wrapping quotes.

**Comment by acebone** [comment]
nope: 

```
$ cat .Xresources-regolith 
#include "/etc/regolith/styles/ayu-mirage/root"

$ cat ~/.config/regolith/Xresources 
i3xrocks.date.format2: %R %A %d. %B %Y

$ cat ~/.config/regolith/Xresources.d
cat: /home/esm/.config/regolith/Xresources.d: No such file or directory

```

I must have edited one of the global files by mistake. I think the "easiest" way to fix it, is to backup my config file, purge regolith and reinstall it. Unless you are interested in pursuing the matter?

**Comment by acebone** [comment]
This is really curious - it seems that I've misunderstood what the problem was all along. The quotes are not part of the setting.

It has actually respected the setting all the way, only - any setting seems to be invalid (except an empty one)

```
$ /usr/share/i3xrocks/time 
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> 16/06 11:03 </span>

$ regolith-look refresh
> Updating already existing 'Regolith' profile
[SUCCESS] Reinstalled Regolith GNOME Terminal version 0.1.0 for the 'Regolith' profile!

$ cat ~/.config/regolith/Xresources 
i3xrocks.date.format2: %R %A %d. %B %Y

$ /usr/share/i3xrocks/time 
date: invalid date ‘%R %A %d. %B %Y’
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> </span>

```

**Comment by acebone** [comment]
The closing was a mistake - but the mystery is solved.

For some reason, I have to prefix the date-format with a plus (like when you use the `date` command)

```
$ xrescat i3xrocks.date.format2
+ %R %A %d. %B %Y

$ /usr/share/i3xrocks/time 
<span color="#e6e1cf"></span><span font_desc="Source Code Pro Medium 13" color="#e6e1cf"> 13:16 Tuesday 16. June 2020 </span>

```
I don't know why I have to prefix a `+` - but my problem is solved, thanks for responding / helping and thanks for updating the help-file :)
