### ISSUE TITLE
Using several lines of code as explanation is not really an explanation

### ISSUE THREAD

**Issue by acebone** [regolith-linux/regolith-linux.github.io#24]
The code-example is fine, but a code-example is a how-to, not an explanation of what is going on.

I suggest you add something like "The directories in  /etc/regolith/i3xrocks/conf.d is prefixed with a number, and it is this number that determines the order of blocks. In order to change the order, you can copy the relevant block-directories to your profiles .config/regolith/i3xrocks/conf.d and change the number-prefixes to reflect the order that you would like" - something along those lines, and then the code-example as a "how-to".

That way a reader would know pretty quickly what is going on, and what he needs to do. As it is now, the user has to mentally parse the code-example, and a novice linux-user risks being rather mystified and think "oh, all that code" and back off.

**Comment by kgilmer** [comment]
Thanks for the suggestion @acebone and I agree with you.  But, it's not clear to me what page you are referring to.  Can you specify?

**Comment by acebone** [comment]
Oh? I used the critique-formular on the wiki page. The one that says "was this page helpful to you?", i thought that the page-id would be POSTed, in an automated userfeedback system?

It is about the configuration of i3xrocks, but I'm currently trying out polybar, so I do not have that directory on my HD anymore - you would probably able to figure it out by looking at the contents of `/etc/regolith/i3xrocks/conf.d`

I think it has to do with ordering of blocks on the i3xrocks statusbar, the name of which I am not quite certain at the moment. 

Files that are ordered by a two-digit-prefix: 

10_something
20_something else
etc

By renaming you can change the order of apperance:

10_somethingelse
20_something

Is that helpful? Too tired to reconstruct now. Let me know if you can't find it. And I'll have a look at a better time.

**Comment by kgilmer** [comment]
Oh, I see.  I shall look into if it's possible to provide the source page when people click the that feedback link, thanks for the extra information.  I also see the content that you pointed out and I agree it could be better.
