### ISSUE TITLE
Clarity of components customization doc

### ISSUE THREAD

**Issue by jasiekmiko** [regolith-linux/regolith-linux.github.io#26]
I would find https://regolith-linux.org/docs/customize/components/ much easier to understand if each row had a short comment about what that component does/is responsible for (at least in the "stock" regolith setup). As someone very new to this whole topic, it would make the entry point much smoother.

**Comment by kgilmer** [comment]
Thanks for the feedback @jasiekmiko !  It's a good idea, we'll update for the upcoming R1.5 release.

**Comment by kgilmer** [comment]
This has been written, closing.
