### ISSUE TITLE
Change Workspace Labels probably needs an update

### ISSUE THREAD

**Issue by ferdinandyb** [regolith-linux/regolith-linux.github.io#28]
The [docs](https://regolith-linux.org/docs/howto/remove-workspace-icons/) now say to stage `/etc/regolith/styles/i3-wm` and edit the user copy of `/etc/regolith/styles/i3-wm` to change names.

It gives the example as 
```
i3-wm.workspace.01.name: 1: Terminal
```

This can also be configured through `~/.config/regolith/Xresources`, but in this as far as I see, you need to add formatting yourself:

```
i3-wm.workspace.01.name: 1:<span font_desc='JetBrains Mono Medium 13'> Terminal </span> 
```

Being able to skip staging is obviously great, but having to add formatting is clunky, so I'm not sure what to do with this now.

**Comment by kgilmer** [comment]
I have updated the documentation to just go with the Xresource approach.  It's much simpler and more consistent than digging into the styles files.  I agree the pango markup is not the greatest but really we're just limited to what i3bar is, until/unless we change to something with higher level abstractions (and more complexity).  

Kindly reopen if my edits to the site do not make sense or I missed something.
