### ISSUE TITLE
Navigating Documentation

### ISSUE THREAD

**Issue by henjen** [regolith-linux/regolith-linux.github.io#29]
Consider adding navigation links to the bottom of each page. Some pages have them, some don't. Like "< Previous" and "Next >". Difficult to navigate using mobile device and scrolling back to the top for the next section. Fantastic DE by the way!

**Comment by kgilmer** [comment]
Thanks for the feedback and kudos @henjen , yes the experience could def be better on mobile devices.  Unfortunately we're using an open source CMS and theme, and this level of customization is not where we want to focus, given the limited time contributors have, and the numerous issues w/ the software itself we wish to address.  If you're interested in contributing we welcome you.  Join us in the slack channel and we can discuss.

Closing now as I want to disable issues in this repo so we do not get orphaned issues here.
