### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by jc00ke** [regolith-linux/regolith-linux.github.io#3]
First off, Regolith looks awesome! I'm running i3 on Manjaro but I kinda miss the Ubuntu world, so I'll be giving this a try.

I noticed that the website isn't served over SSL. It looks like you have most things ready to go, so on [the settings page](https://github.com/regolith-linux/regolith-linux.github.io/settings) page you can check the *Enforce HTTPS* checkbox and you'll get a cert.

**Comment by kgilmer** [comment]
Thanks for the kind words and the tip on the SSL configuration, @jc00ke !  And you made me a link even, so nice!
