### ISSUE TITLE
Revamp Regolith landing page for R1.2 release

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-linux.github.io#5]
* move all but one screenshot to new dedicated page for them.
* in new page, add details for login, Xresources, files, settings, tray, multiple themes, etc.
* in landing page add section that defines what makes Regolith different
* Reword intro to be more new-user friendly.

**Comment by ahoneybun** [comment]
1 - Which screenshot is not moving?
3 - Would this tie into the rewrite in the 4th point?

**Comment by kgilmer** [comment]
Hi @ahoneybun , here's some more detail as to what I am thinking for the site update.  It's def open to discussion and tweaking as needed.

1- We can just use filenames and worry about particular screenshots later once the UI is stable.  For the main page maybe something like assets/regolith-intro.png.  For the screenshot page, I'm thinking something like:

1. regolith-empty.png (empty desktop)
2. regolith-solarized.png (solarized w/ 3 terminals, no gaps in 2 / 1 / 1 configuration)
3. regolith-gruvbox.png (grovbox theme w/ `/etc/regolith/styles/root` on an open editor, floating, conky cheat-sheet)
4. regolith-gnome.png (page w/ control center, mounted USB volume, software store, and maybe logout dialog, with thick gaps)
5. regolith-rofi- (empty desktop w/ rofi app dialog)
6. regolith-rofi-windows (empty desktop, rofi window dialog)


3- yeah so the intro dives right into gnome/i3 integration, but this is probably too technical for the average user, so a more general purpose descriptoin for the first paragraph.  Then, the single screenshot section w/ link to the screenshot page, then a section on "Why Regolith?" (exact title tbd) w/ a list of headlining features (such as tiling wm, ubuntu, easy ricing, etc.)

Following the "Why Regolith" section would continue to be "Get Regolith".  TBH I'm not sure to keep this as-is or truncating and extracting to a seperate page.  Probably the latter w/ code snippets for PPA install and links to PPAs, ISO download page.

Last, as is there now, a summary of what else is on the site, w/ more details and links to most if not all pages.

**Comment by kgilmer** [comment]
- Title
  - Regolith intro paragraph
- Looks
  - Intro screenshot
  - Link to screenshots page
- Regolith Details section
  - Bulletted list of Regolith top-level features
- Get Regolith section
  - Link to ISO download
  - Brief line describing PPA URL and top-level package
  - Link to "get Regolith" page
- Site Summary
  - Describe pages on site, ordered by likely interest of a new user

**Comment by ahoneybun** [comment]
1-4. regolith-gnome.png (page w/ control center, mounted USB volume, software store, and maybe logout dialog, with thick gaps)

I won't be able to do that screenshot as I have Pop OS installed with Regolith Desktop installed on top.

Are all of those points on the intro page then? What would be the intro screenshot?

**Comment by ahoneybun** [comment]
How would we grade how interested a new user would be for a new page?

**Comment by ahoneybun** [comment]
WIP here: https://github.com/ahoneybun/regolith-linux.github.io/blob/master/index.md

**Comment by kgilmer** [comment]
> I won't be able to do that screenshot as I have Pop OS installed with Regolith Desktop installed on top.

No sweat.  I'll produce the screenshots.

> Are all of those points on the intro page then? What would be the intro screenshot?

The intro screenshot will be a /r/unixport style floating window shot that's more about flash than substance.  I can provide that.  The points on the intro, maybe something like:

## Why Regolith

* Provides GNOME's system management features with i3's productive workflow.
* Enables new users a fast and fun way to try out the i3 window manager environment.
* Supports easy customization and ricing via a consistent Xresource configuration.
* Relies on Ubuntu's app store and package repositories for a large, high quality selection of software. 
* Delivers a desktop with small set of UI features that can be customized and expanded as needed.
* Ships with an overlay of basic keybindings to navigate over windows, launching apps, and managing your system.

**Comment by ahoneybun** [comment]
Those are really good, I'll use those.

**Comment by kgilmer** [comment]
Intro paragraph draft:

Regolith is a unique desktop environment that ditches the cruft of Windows and Mac derivatives to provide clean, productive, and beautiful place to get work done.  Built on top of Ubuntu and GNOME, Regolith offers a stable, well-supported, and consistent foundation.

**Comment by ahoneybun** [comment]
That could work.

**Comment by kgilmer** [comment]
Thank you for making all of these changes on your branch @ahoneybun !  I'll continue to review this week.

**Comment by ahoneybun** [comment]
Glad to help out!

**Comment by ahoneybun** [comment]
The Screenshot page is the one that needs the most work current with new screenshots and if there should be any descriptions below/above them.
