### ISSUE TITLE
In installation docs, for uninstallation, mention both `regolith-desktop` and `regolith-st` must be removed.

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-linux.github.io#6]
Fixes https://github.com/regolith-linux/regolith-desktop/issues/51

**Comment by ahoneybun** [comment]
Would it be better to make it so that when you run 'apt autoremove' it pulls out 'regolith-st'? Or package 'regolith-desktop' in a way that removing it removes 'regolith-st' as well?

**Comment by kgilmer** [comment]
Yes, it certainly would, but I'm not aware of a clean way of doing that.  LMK if you have any suggestions! :smile:
